buildscript {
	dependencies {
		classpath group: "com.liferay", name: "com.liferay.gradle.plugins", version: "14.0.95"
	}

	repositories {
		maven {
			url "https://repository.liferay.com/nexus/content/groups/public"
		}
	}
}

apply plugin: "com.liferay.plugin"

def targetVersion = '7.3.10.u17'

dependencies {
	compileOnly platform('com.liferay.portal:release.dxp.bom:' + targetVersion)
	compileOnly platform('com.liferay.portal:release.dxp.bom.third.party:' + targetVersion)
	compileOnly platform('com.liferay.portal:release.dxp.bom.compile.only:' + targetVersion)
	compileOnly group: "com.liferay.portal", name: "com.liferay.portal.impl"
	compileOnly group: "com.liferay.portal", name: "com.liferay.portal.kernel"
	compileOnly group: "javax.portlet", name: "portlet-api"
	compileOnly group: "javax.servlet", name: "javax.servlet-api"
	compileOnly group: "org.osgi", name: "osgi.cmpn"
}

repositories {
	mavenLocal()

	maven {
		url "https://repository.liferay.com/nexus/content/groups/public"
	}
}
